Encoding/x265Enc.vb
x265 official Preset Options (https://x265.readthedocs.io/en/default/presets.html) state that early-skip is enabled for presets ultrafast, superfast, veryfast, fast, and medium. The medium preset was changed to incorporate this value.
x265 official Command Line Options (https://x265.readthedocs.io/en/default/cli.html) state that psy-RDOQ has a value of 1.00 for presets slow, slower, and veryslow. These presets were changed to incorporate this value.
=> Change default values of Early Skip and Psy-RDOQ for various presets

Encoding/x265Enc.vb
I realized I hadn't complete the process of updating the preset default values. The original commit modified the ApplyPresetValues() function, but this one includes the ApplyDefaultPresetValues() function changes as well. This affects command line arguments that are set or not set depending on the default values in the latter function.
=> Changed default preset values for Early Skip and Psy-RDOQ (Part 2)

General/Demux.vb
The -map 0 option causes an error in some cases.
=> Update Re-mux command line for ffmpeg

Encoding/x264Enc.vb, Encoding/x265Enc.vb
Step size should be 0.5 in order to be more compliant with other step sizes and to its possible values - value of 1 is a little bit too  extreme/huge.
=> Change CRF step size from 1 to 0.5

Changelog.md, Forms/MainForm.vb, General/ApplicationSettings.vb, General/Update.vb
At the moment beta versions are only scrapped from DropBox. The link to the DropBox folder is hardcoded. If it's not reachable, the current/changed DropBox link if fetched from the docs (https://staxrip.readthedocs.io/introduction.html).
**If  the DropBox folder/link changes, the code should be adjusted to prevent unnecessary web queries.**
---------------------
=> Include beta versions for update checker and show changelog

Forms/MainForm.vb
With this extension this is possible now:
`D:\> staxrip.exe video.mkv`
`D:\MusicVideos> staxrip.exe .\video.mkv`
`D:\> C:\Apps\StaxRip\staxrip.exe .\Music\video.mkv`
`D:\Videos> C:\Apps\StaxRip\staxrip.exe ".\video to test.mkv"`
...which is very very useful when you work with CommandPrompt/PowerShell.
Before you got DirectoryNotFoundExceptions and/or problems due to relative directories inside the filer scripts.
=> Open relative paths

Forms/MainForm.vb
Created 4 separate methods for each category to make those commands selectable, too.
Due to irritations and probable problems I decided at the moment to not create a sub menu for them and also to not rename `ShowOpenSourceDialog()` to move it alphabetically above the single selection options - but that can be improved afterwards.  🙂
=> Add 4 commands to open each source category separately

Forms/MainForm.vb, General/Extensions.vb, General/JobManager.vb, UI/Controls/Controls.vb
This basically extends #269 to give better and more intuitive usage possibilities.
Also solves the problem with pressed modifier keys and opening message boxes in between.
------
- Change bnSkip_Click() to bnNext_Skip() (see #268)
- Add possibility to add new jobs at specific position (see #269)
- Add ContextMenu to bnNext for all 4 possible options (to top/bottom / w/(o) opening Jobs)
- Change button text when modifier keys are pressed
--------
=> bnNext extension (includes #268 and #269)

Changelog.md
#265 was merged, but the change is gone - History of Changelog.md doesn't show any commits that deleted it.  🤨
=> Re-fix v2.1.3.7 DGIndex enabled by default (Changelog)

Encoding/x265Enc.vb
Fixes Presets and Tunes for x265 encoder. 
Some values are fixed, biggest changes:
- b-frames in *Tune Animation* don't get a static value. According to the x265 docs b-frames should be "increased by 2".
- Introduced `RSkip` as Property and includes it in presets and tunes - options `Undefined` and `3` were removed
- Moved `--rskip-edge-threshold` NumParam from `Analysis 2` to `Analysis` next to `RSkip`
=> Fixes x265 Presets and Tunes

Changelog.md, Forms/ProcessingForm.vb, General/General.vb, General/GlobalClass.vb, General/Proc.vb, General/ProcController.vb
I think this screenshots explains everything:
There are two things I wanna point on:
- I extended the context menu with *Skip* **and *Abort*** for the sake of completeness and didn't touch the *Abort* button. Personally I would remove the *Abort* button, but it's up to you which combination you wanna use/add.
- I tried to implement the *Skip* feature based on your implementation of the *Abort* process. Therefore I used `TaskCancelledException`, because it kind of fits and I didn't want to create a custom/derived exception for only that purpose. Feel free to change it if it bothers you.  🙂 
Hope I didn't forget any aspect of skipping these (very) complex processes. In my little test cases it worked great.
=> Skip running process

General/VideoScript.vb
When selecting AVS filters AssumeFPS, ChangeFPS and ConvertFPS, the choices of frame rates will be displayed as decimal, but the actual filter will use the (num,den) format. E.g. the user will select 23.976, and the filter will use (24000,1001).
=> Fix frame rates for AviSynth functions

General/Package.vb, docs/generated/tools.rst
To http://avisynth.nl/index.php/GradFun2DBmod
=> Fix incorrect GradFun2DBmod Web address

General/Package.vb
Previous AVS SMDegrain  filter profiles were not very meaningful. These ones match better common usage.
Also, Contrasharp=true call does not work anymore due to recent update in RGTools.
So these NEW filter profiles do not use Contrasharp=true anymore.
=> Rework of AVS SMDegrain to match popular use

General/Package.vb
Underlying filters have been updated, so contrasharp=true parameter is working now.
=> SMDegrain: reinstate contrasharp true parameter

License.txt
Typo: "association" was missing first letter, copyright year was still 2020.
=> Fix typo and copyright date in License

Source/Encoding/x265Enc.vb
Not mentioned in the docs, but it's in the code: https://github.com/DJATOM/x265-aMod/blob/aMod-3.4-new/source/common/param.cpp or https://bitbucket.org/multicoreware/x265_git/src/master/source/common/param.cpp
=> x265 fix tskip default value for placebo preset

Source/General/Package.vb
After update of mtn to 3.4.0, this description is no more valid.
=> Remove invalid paragraph in mtn description

Changelog.md
the correct version name is Clang W7 AVX 😁
=> Typo in Changelog

Source/Video/VapourSynthFilterProfileDefaults.txt
Per User jinkazuya's request in Doom9 forum, `G41Fun.DetailSharpen` filter profile is added in VS default profiles.
Since `G41Fun` is included as a native VS Scripts package in StaxRip, there is no dependency issue.
=> DetailSharpen VS profile added

Source/General/ApplicationSettings.vb
This allows post processing tasks like thumbnail creation to be able to complete before shutdown happens.
=> Set initial Shutdow Timeout to 90 seconds

Source/Video/AviSynthFilterProfileDefaults.txt
AVS Interframe: ordered parameters as per the author's doc, added more guiding info, and added 3D processing options.
YFRC: typo (was misspelled YRFC)
=> AVS Filters InterFrame and YFRC adjustments

Source/Encoding/AOMEnc.vb
Just a bit of a sweep of updates for new settings and defaults etc for aomenc, as well as some fixes.
- Fixed Vapoursynth not working because it was adding an `=` to the skip and limit commands which aren't valid inputs to vspipe
- Fixed a few `AlwaysOn` settings where they were missing / unneccesary
- Added the ability to set the target bitrate when using constrained quality mode
- Added a grain related settings submenu to avoid cluttering `AV1 Specific 6`
- Added `--enable-dnl-denoising`
- Added new `--tune` options
- Fixed incorrect `--tune` values
- Added new `--deltaq-mode` options
- Added `--deltaq-strength` (Only works in delta-mode 4 for now)
- Added new `--tune-content` option
- Increased max number of chunks, this is a bit of a workaround for using the experimental keyframe …
=> Updates & Fixes for AOMEnc

Source/General/Audio.vb, Source/General/Misc.vb
Closes #997 
Tested and confirmed working by manually performing the commands StaxRip uses to create the dummy/filler file and perform the subsequent cut.
=> Fix audio (and subtitle) cutting issues caused by ffmpeg upstream

Source/Encoding/SvtAv1.vb
--key-init 'Intra Period' has a default value of -2, instead of current value -1.
Reference: https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md?plain=1#L220
=> Update SvtAv1.vb: Set '--key-init' to default value of -2

Source/General/Package.vb, Source/Video/VideoScript.vb
instead of checking the script for each function this PR tries to figure out what function are used and uses the resulting hashset for usage checking which is much faster than checking the whole script for each plugin
=> improve script update performance
