staxrip/staxrip

- Encoding/NVEnc.vb
> minor change

- General/VideoScript.vb
> Update Vapoursynth filter

- Encoding/NVEnc.vb
set values with point instead of decimal point
> Fix for issue #171

- Encoding/VideoEncoder.vb
> Fix for issue #172

- General/Native.vb
> Taskbar Progress always indicating running process

- General/ProcController.vb
In addition to Pull Request  #187 this also works when encoding.
Code tested, works as expected.
> Taskbar Progress always indicates running process

- Forms/MainForm.vb
> Corrected Typos

- Changelog.md
> v2.1.3.7 DGIndex enabled by default (Changelog)

- Forms/MainForm.vb
Just to be compliant with its button name
> Rename bnSkip_Click() to bnNext_Click()

- Changelog.md
- Forms/MainForm.vb
- General/JobManager.vb
Implements #220
For you knowledge:
position | resulting position in list
-----|-----
... | ...
-3 | third last
-2 | seconds last
-1 | last (default)
0 | first
1 | second
2 | third
... | ...
> Adds modifier keys for NEXT button (#220)

- Forms/JobsForm.vb
- Forms/MainForm.vb
- Forms/ProcessingForm.vb
Create F6 shortcut for Jobs on ProcessingForm.
Compliant to the F6 shortcut on MainMenuStrip.
> Create F6 shortcut for Jobs button on ProcessingForm

- General/GlobalClass.vb
It's absolutely annoying when a few windows opens suddenly without any notice.
Especially the browser can slow down your PC and ruin saved sessions.
> BugReport: Ask before opening files/windows

- Encoding/x265Enc.vb
Issue from [here](http://forum.doom9.org/showthread.php?p=1921005#post1921005)
> fix: x265 three pass encoding

- General/Package.vb
There's no such filter as `Repair16`.
Dither package provides `Dither_Repair16` instead.
> Replace Rapair16 with Dither_Repair16

- Encoding/AOMEnc.vb
Value between 1 and 9999 not 0 and 9999
> Aomenc kf-max-distance value range

- General/Package.vb
SMDegrain syntax adapted to newer build that accepts native 10+ bit depth
> SMDegrain (AVS) Filter syntax update

- Changelog.md
- Source/Encoding/x265Enc.vb
> x265 fix slower preset defaults

- README.md
> Update README.md Grammar & Style 

- README.md
Correction of labels for "Release" and "Beta"
> Release and beta label adjustment in Update README.md

- Source/Forms/MainForm.vb
Make help text for settings > binary prefix more elaborate
> Help for settings > binary prefix

- README.md
README polish-ups and minor fixes in accordance with the new versioning scheme.
> Polish-ups and fixes for README

- Source/General/Package.vb
> Items for yadifmod2 and JincResize updated

- Source/Video/AviSynthFilterProfileDefaults.txt
Relabeled some filters, improved the Color Debanding section by adding Neo_f3kdb, and reworking Gradun3...
> Improve some Restoration filters in AVS

- Source/Video/AviSynthFilterProfileDefaults.txt
Added a few options to that tweak filter.
> Improve AVS filter "Tweak"

- Source/Video/AviSynthFilterProfileDefaults.txt
Added Decimate, Line selecting/discarding, Field swapping. Improved TDeint and yadifmod2. Renamed former "Select" to "SelectField".
> Improve and add filters in the AVS Field section

- Source/Video/AviSynthFilterProfileDefaults.txt
Small typo fix addressing #650.
> Fix AssumeBFF

- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
Added the `Sharpen` filter to default AVS/VS filter profiles.
> Add Sharpen to default AVS/VS profiles

- Source/General/Package.vb
- Source/Video/AviSynthFilterProfileDefaults.txt
The recommended place for `CAS.dll` is `<StaxRip-Folder>\Apps\Plugins\AVS\CAS`.
(Reminder: plz put the `x64` build. 😁)
> Add AVS filter CAS and its profile script

- Source/Video/VapourSynthFilterProfileDefaults.txt
VS `CAS` filter profile script is added.
> Add CAS filter profile for VapourSynth

- Source/General/Package.vb
- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
DAA3Mod, FineSharp, HQDeringmod, LSFmod, MAA2Mod, ResizeX, etc.
> Update various AVS packages URLs and info

- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
Used American English spelling for consistency with `mvsfunc.GrayScale()`. 😁
> Add Grayscale filter profiles (AVS, VS)

- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
> Update filter profiles

- Source/Video/AviSynthFilterProfileDefaults.txt
Add AVS SeparateFields filter.
> Add AVS SeparateFields filter

- Source/General/Package.vb
- Change `HelpURL` to the corresponding AviSynth wiki page
- Add `HelpFilename`
- Update `Description`
- Add `TemporalRepair` in the filter list
> Update RgTools URLs, description, and filter list

- Source/General/Package.vb
- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
- Update AVS `SelectEvery` filter profile: removed a misleading comment line
- Add AVS/VS `FillDrops` filters, AVS `DeJump` filter
- Add AVS `RT_Stats`, `ExactDeDup` filters
- Add AVS `Fix Horizontal Rainbow` filter profile
> Filter Updates

- Source/General/Package.vb
- Fix VS `filldrops` plugin item name for namespace compatibility with the filter (case sensitivity)
> Filter Updates Patch

- Source/Video/AviSynthFilterProfileDefaults.txt
- Source/Video/VapourSynthFilterProfileDefaults.txt
- Add `NNEDI3_rpow2`(AVS/VS) filter profiles
- Add `HDRTools`(AVS) _HDR to SDR_ filter profiles
> Filter Profile Updates

- Source/Encoding/x265Enc.vb
- Source/General/Package.vb
> x265 Fixes
